-- 10-dev-only.sql · fixture data for local/dev ONLY: never applied to prod.
-- Dev sermons, pre-approved testimonies/prayers, test events land here as their
-- work items arrive (W1.3, W1.5, W1.7). Prod seeding goes through the reviewed
-- step in docs/spec/19 instead.
