import { defineConfig, globalIgnores } from 'eslint/config';
import prettier from 'eslint-config-prettier/flat';
import agbcBase from '@agbc/eslint-config/base';

export default defineConfig([
  // Generated by `supabase gen types`; must stay byte-identical to the generator's
  // output for CI's types-drift gate, so neither lint nor prettier touches it.
  globalIgnores(['src/database.types.ts']),
  ...agbcBase,
  prettier,
]);
